### ISSUE TITLE
I cant add html element;

### ISSUE THREAD

**Issue by mtemel123** [veu/mini-tetris#6]
How do I create ui element in under tetris? My purpose just create `<b>lorem imp</b>` in body ?

**Comment by veu** [comment]
It uses `innerText` to replace everything in the body with the UI. You can either let it write into a different element like this

```
<body onload="…"style=font:2em/.6''><p id=Z><p>lorem ipsum
```

or you add it to `innerText` after the UI:

```
…
S|=b.map(v=>{S+=`
`;for(x=10;x--;)Z.innerText=S+='□■'[G^(v^1023+P&&v>>x&1)]}),
Z.innerText+='<b>lorem ipsum'
…
```

**Comment by mtemel123** [comment]
its work. thank u for your solution. mini-tetris is awesome.
