### ISSUE TITLE
474bytes(utf-8)

### ISSUE THREAD

**Issue by da0ka** [veu/mini-tetris#9]
<body id=D onkeydown=K=event.keyCode-38 onload="Z=X=[B=A=12];function Y(){for(C=[q=c=i=4];f=i--*K;c-=!Z[h+(K+6?p+K:C[i]=p*A-(p/9|0)*145)])p=B[i];for(c?0:K+6?h+=K:t?B=C:0;i=K=q--;f+=Z[A+p])k=X[p=h+B[q]]=1;h+=A;if(f|B)for(Z=X,X=[l=228],B=[[-7,-20,6,h=17,-9,3,3][t=++t%7]-4,0,1,t-6?-A:2];l--;)for(l%A?l-=l%A*!Z[l]:(P+=k++,c=l+=A);--c>A;)Z[c]=Z[c-A];for(S=P;i<240;S+=X[i]|(X[i]=Z[i]|=++i%A<2|i>228)?'■':'　')i%A||(S+='\n');D.innerText=S;Z[5]||setTimeout(Y,i-P)}Y(h=K=t=P=0)">

**Comment by da0ka** [comment]
<body id=D onkeydown=K=event.keyCode-38 onload="Z=X=[B=A=12];function Y(){for(C=[q=c=i=4];f=i--*K;c-=!Z[h+(K+6?p+K:C[i]=p*A-(p/9|0)*145)])p=B[i];for(c?0:K+6?h+=K:t?B=C:0;i=K=q--;f+=Z[A+p])k=X[p=h+B[q]]=1;h+=A;if(f|B)for(Z=X,X=[l=228],B=[[-7,-20,6,h=17,-9,3,3][t=++t%7]-4,0,1,t-6?-A:2];l--;)for(l%A?l-=l%A*!Z[l]:(P+=k++,c=l+=A);--c>A;)Z[c]=Z[c-A];for(S=P;i<240;S+=X[i]|(X[i]=Z[i]|=++i%A<2|i>228)?'■':'　')i%A||(S+='\n');D.innerText=S;Z[5]||setTimeout(Y,i-P)}Y(h=K=t=P=0)">

**Comment by da0ka** [comment]
base64 encoded
PGJvZHkgaWQ9RCBvbmtleWRvd249Sz1ldmVudC5rZXlDb2RlLTM4IG9ubG9hZD0iWj1YPVtCPUE9MTJdO2Z1bmN0aW9uIFkoKXtmb3IoQz1bcT1jPWk9NF07Zj1pLS0qSztjLT0hWltoKyhLKzY/cCtLOkNbaV09cCpBLShwLzl8MCkqMTQ1KV0pcD1CW2ldO2ZvcihjPzA6Sys2P2grPUs6dD9CPUM6MDtpPUs9cS0tO2YrPVpbQStwXSlrPVhbcD1oK0JbcV1dPTE7aCs9QTtpZihmfEIpZm9yKFo9WCxYPVtsPTIyOF0sQj1bWy03LC0yMCw2LGg9MTcsLTksMywzXVt0PSsrdCU3XS00LDAsMSx0LTY/LUE6Ml07bC0tOylmb3IobCVBP2wtPWwlQSohWltsXTooUCs9aysrLGM9bCs9QSk7LS1jPkE7KVpbY109WltjLUFdO2ZvcihTPVA7aTwyNDA7Uys9WFtpXXwoWFtpXT1aW2ldfD0rK2klQTwyfGk+MjI4KT8n4pagJzon44CAJylpJUF8fChTKz0nXG4nKTtELmlubmVyVGV4dD1TO1pbNV18fHNldFRpbWVvdXQoWSxpLVApfVkoaD1LPXQ9UD0wKSI+

**Comment by veu** [comment]
@da0ka Your version is significantly different in UI and functionality compared to the current master. Are any of the optimizations applicable without changing the result?

**Comment by da0ka** [comment]
sorry, I have no idea.
